# Generated by Django 4.0.5 on 2022-08-27 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drive.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=drive.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent_folder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
